### ISSUE TITLE
`Info` option in the context menu of a js-engine codeblock ?

### ISSUE THREAD

**Issue by I-Pch** [mProjectsCode/obsidian-js-engine-plugin#11]
Hi there 😄 !

So I installed JS Engine for the first time last night and I just wanted to know: 

What's the `Info` option in the context menu of a `js-engine` codeblock ? 😊  (the context menu being the one we can access when hovering the codeblock, which also contains the option to `Rerun`)
What is it supposed to do ?

I'm asking because when I select `Info` in the menu, all I get is an empty modal I can only close 😄  (Both on Desktop and Mobile) ...

<img width="690" alt="JS Engine - Context menu" src="https://github.com/mProjectsCode/obsidian-js-engine-plugin/assets/77828085/d982bc12-8801-4e1f-9c4a-a0a4fbd45a68">

<img width="690" alt="JS Engine - Info Modal" src="https://github.com/mProjectsCode/obsidian-js-engine-plugin/assets/77828085/f77c37a6-2f76-4bbd-ab86-e27ba3dc58c3">

Sorry for the newbie JS Engine question 🙈 ... But thank you very much in advance for shedding some light on this 💡 😁 !

---
Edit: Oh! I just checked in the console and I get this error each time I select `Info` in the menu 😅  :
```
Uncaught TypeError: Cannot read                 plugin:js-engine:45    
properties of undefined (reading 'highlight')
    at n.$$.update (plugin:js-engine:45:65891)
    at Z (plugin:js-engine:44:4858)
    at new Ws (plugin:js-engine:45:66001)
    at Uo.onOpen (plugin:js-engine:45:66352)
    at e.open (app.js:1:1455869)
    at Go.openExecutionStatsModal (plugin:js-engine:45:66940)
    at Bo.openStatsModal (plugin:js-engine:45:61948)
    at eval (plugin:js-engine:45:1487)
    at e.handleEvent (app.js:1:1169857)
n.$$.update               @ plugin:js-engine:45
Z                         @ plugin:js-engine:44
Ws                        @ plugin:js-engine:45
onOpen                    @ plugin:js-engine:45
e.open                    @ app.js:1
openExecutionStatsModal   @ plugin:js-engine:45
openStatsModal            @ plugin:js-engine:45
eval                      @ plugin:js-engine:45
e.handleEvent             @ app.js:1
``` 

I only have 2 other plugins installed and enabled (Templater & Logstravaganza) in that vault, latest version of Obsidian (`1.5.12` - Installer `1.5.8`) no theme and no CSS snippet 😊

**Comment by mProjectsCode** [comment]
huh, it seems like something with the highlighting fails there. Will take a look later today.

**Comment by I-Pch** [comment]
I can confirm happily confirm that `0.1.5` fixes the `Info` issue both on Desktop and Mobile 🙌 😁 !!!

Thank you for investigating this and the more than very fast fix 🎉 🙌 !
