### ISSUE TITLE
Sample Vault: One of the example doesn't seem to work... 

### ISSUE THREAD

**Issue by I-Pch** [mProjectsCode/obsidian-js-engine-plugin#12]
Hi there 😄 !

I am awfully sorry (😅) but while playing around with/exploring the examples in the sample vault, I stumbled upon one that doesn't seem to work (anymore ? 🤷‍♀️ )/ play well with Meta Bind (which is installed and enabled 😊)

The concerned example is the "Meta Bind" test 😊 : [here](https://github.com/mProjectsCode/obsidian-js-engine-plugin/blob/9978dd39a18406d0dee0b76dd4311dc0c6857428/exampleVault/Test.md#meta-bind-test), specifically the lines: 
- [L155](https://github.com/mProjectsCode/obsidian-js-engine-plugin/blob/9978dd39a18406d0dee0b76dd4311dc0c6857428/exampleVault/Test.md?plain=1#L155)
- [L156](https://github.com/mProjectsCode/obsidian-js-engine-plugin/blob/9978dd39a18406d0dee0b76dd4311dc0c6857428/exampleVault/Test.md?plain=1#L156)

... in which, apparently: 
```
mb.createInputFieldFromString is not a function
``` 
... I guess it should be something like: `createInlineFieldFromString` or a similar one ? 😊 

This is a detail but I just wanted to let you know 😊 .

**Comment by mProjectsCode** [comment]
yeah, they use pre 1.0 meta bind APIs which no longer work
