### ISSUE TITLE
Is it possible to embed code blocks inside tables?

### ISSUE THREAD

**Issue by claremacrae** [mProjectsCode/obsidian-js-engine-plugin#17]
I have been using DataView to generate tables that contain code blocks.
The code blocks are of course Tasks searches.

I am hoping to replace this with using js-engine to generate tables with code blocks.

### Table with single-line cells

This `js-engine` code block creates a trivial table:

~~~js
let markdownBuilder = engine.markdown.createBuilder();
markdownBuilder.createTable(['col1', 'col2'], [['value 1', 'value 2']]);
return markdownBuilder;
~~~

![image](https://github.com/mProjectsCode/obsidian-js-engine-plugin/assets/4840096/944574cb-a4bc-4a15-90a5-29a107c6c49e)

### Attempt at creating table with a code block in

I've tried various iterations of this `js-engine` code block to create a table with a code block in:

```js
let markdownBuilder = engine.markdown.createBuilder();
let codeBlock = `~~~text
Hello World
~~~`
markdownBuilder.createTable(['col1', 'col2'], [['value 1', codeBlock]]);
return markdownBuilder;
```

They all seem to display some of the code block text outside the table...

![image](https://github.com/mProjectsCode/obsidian-js-engine-plugin/assets/4840096/1d3ff18a-fbe4-4044-a61d-5ada1d6c508b)

### The question!

Is it currently possible to put (rendered) code blocks inside js-engine tables please?

**Comment by mProjectsCode** [comment]
No, the markdown spec does not allow that. The markdown builder generates an actual markdown string which is then passed to Obsidians markdown renderer.

**Comment by claremacrae** [comment]
Ah right, OK thanks.

Is there a way to use js-engine to build raw HTML then?

**Comment by mProjectsCode** [comment]
It's JavaScript, so you can use the normal web APIs. Global Obsidian helper functions and prototype extensions should work as well.

**Comment by mProjectsCode** [comment]
Things exported under the obsidian namespace should be available via the `obsidian` object, so e.g. `new obsidian.Notice("hello")`

**Comment by claremacrae** [comment]
Ah well, thank you very much for the replies.

**Comment by mProjectsCode** [comment]
The only way I see to get code blocks into tables would be to use HTML tables, but then the codeblocks would need to be created with HTML as well and markdown post processors wouldn't run on those.

**Comment by claremacrae** [comment]
Understood. I have no idea how dataview manages it, but it does. So that is always available as a fall-back.

**Comment by claremacrae** [comment]
Any chance you could change this from completed to won’t fix, though please, for transparency.
