### ISSUE TITLE
[FR] Remove unnecessary log

### ISSUE THREAD

**Issue by Mara-Li** [mProjectsCode/obsidian-js-engine-plugin#19]
Additional FR here : https://github.com/mProjectsCode/obsidian-meta-bind-plugin/issues/384

The plugin seems to print the content of each blocks in the console, that leads to an enormous content of the console. Duplicated sometomes by meta-bind itself. Sometimes, the amount of the logs can be more than 1000 lignes.

[Plugin guildelines](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Avoid+unnecessary+logging+to+console) state we should avoid unncessary logging to the console, so the plugin should be updated in accordance.

**Comment by mProjectsCode** [comment]
I am not 100% sure what you are referring to. The plugin logs the markdown string it renders [here](https://github.com/mProjectsCode/obsidian-js-engine-plugin/blob/e8a39f33057d9a2dcb62791bf0845b99ba7387d4/jsEngine/engine/ResultRenderer.ts#L48) (this should probably be removed or turned into a debug log).

**Comment by Mara-Li** [comment]
I made a draft PR to show you the faulty line that create the log spamming issue

**Comment by mProjectsCode** [comment]
this should all be done. Thanks for the issue and PR
