### ISSUE TITLE
Create some great examples

### ISSUE THREAD

**Issue by Gourav1910** [mProjectsCode/obsidian-js-engine-plugin#2]
Templater was a great plugin but to fully understand its potential they created various amazing templates such as the template in which we can generate movie notes So if you also develop some useful example then this plugin will go viral for its potential I want you to develop some useful examples for non coders so that they can copy and paste the code and just use it

**Comment by mProjectsCode** [comment]
The idea to provide examples is good and something that I already had planned.
But it would be great if you could word your requests more carefully. I and most other developers of projects on GitHub are not paid and are working on their projects in their free time. Maybe you can find some more friendly and considerate words than `I want you to ...`. :)

**Comment by Gourav1910** [comment]
> The idea to provide examples is good and something that I already had planned. But it would be great if you could word your requests more carefully. I and most other developers of projects on GitHub are not paid and are working on their projects in their free time. Maybe you can find some more friendly and considerate words than `I want you to ...`. :)

Are you lost your mind🙄? When did I abuse you? I just submitted a request that I think could be useful for me and various people. And I used very friendly language. I don't know what other way you want me to submit my request. Do you want me to first bow down and surrender to you?? Now I am using strong language consciously because you already blamed me for what I never did. I didn't use any abusive or wrong word that indent to harm anyone. I just wrote the request simply the way everyone write. Now if you don't wanna do it or can't do it that's your problem. But if you have made a plugin and allow people to submit their requests then I have complete rights to write my request. Now drink some clean water to improve your comprehension.😠

**Comment by mProjectsCode** [comment]
> When did I abuse you?
I never accused you of that. I merely asked you to word your requests a bit more friendlier, but it seems like you are unable to do so. Please do not contact me again.
