### ISSUE TITLE
How to trigger execution of a code block

### ISSUE THREAD

**Issue by ujikol** [mProjectsCode/obsidian-js-engine-plugin#22]
I recognize no new functionality beside the command Execute JS File.

How can I execute a code block? There is no command, no icon in any bar, no icon at the code block.

Not a word about it in the readme and the documentation.

**Comment by ujikol** [comment]
Ah, the trigger is your own "language".
Is there a way to activate syntax highlighting like in js blocks?

**Comment by mProjectsCode** [comment]
The `js-engine` code blocks should have the same highlighting as normal `js` code blocks.

![image](https://github.com/user-attachments/assets/92b4dce4-41f2-463a-b351-3d11c8424476)
