### ISSUE TITLE
js-engine vs. dataviewjs

### ISSUE THREAD

**Issue by ujikol** [mProjectsCode/obsidian-js-engine-plugin#24]
Sorry for raising it here. I have no hint in the documentation where to discuss better.

What makes this plugin different from dataviewjs? Where is it more appropriate to use?

And maybe this would be worth to mention in the docs.

thx

**Comment by mProjectsCode** [comment]
There is not a lot of difference. Both plugins can run JS, but the JS Engine API is nicer imo.
