### ISSUE TITLE
Use CSS Snippets

### ISSUE THREAD

**Issue by zauberparacelsus** [mProjectsCode/obsidian-js-engine-plugin#26]
Would it be possible to add a way for the markdown builder to include the enabled CSS snippets for an obsidian notebook?

I am using JS-engine to generate embeds for subsections in files within a folder, and use custom CSS to hide the header in the embed.  This hiding works elsewhere in the notebook, but not in what is generated by this plugin

**Comment by mProjectsCode** [comment]
CSS snippets apply globally to everything. This is probably an issue with your CSS snippet.
