### ISSUE TITLE
Obsidian doesn't recognize js engine

### ISSUE THREAD

**Issue by Devilofether** [mProjectsCode/obsidian-js-engine-plugin#27]
The file appears to be missing main.js. I also have custom js and meta bind installed, trying to execute a script using a button.
![Capture](https://github.com/user-attachments/assets/49c73311-9e97-40e2-931e-013fa32e1ed2)

**Comment by mProjectsCode** [comment]
The latest release has all the files. Maybe it got deleted on your drive for some reason. Try reinstalling the plugin or if that does not work manually download the missing files.

**Comment by mProjectsCode** [comment]
Will close due to inactivity
