### ISSUE TITLE
Reply

### ISSUE THREAD

**Issue by Gourav1910** [mProjectsCode/obsidian-js-engine-plugin#3]
If you dare to speak then dare to listen as well. Show my message to 10 of your random friends and ask them is there anything offensive in that. You clearly need some rest. I submitted that issue with the intention that it would get more success if you could add more examples for the non technical user who don't know coding but can use the plugin like templater by copy and pasting. But instead of understanding it you are in your own world. That's the difference between successful people and ever crying people. Successful people listen to the feedback and improve on it. Feedback is the best currency for any creator. But I don't care. Keep crying your full life. The person who can't figure out what is beneficial for him can't understand anyone else. And if you dare to reply then dare to listen as well instead of running away by hiding your face. I am even gonna show my submitted request to the obsidian community and expose you that what is something wrong language in my request. It is a common language people speak to submit the request. Ok now go cry.

**Comment by mProjectsCode** [comment]
If you read my reply to your original comment, then you would have noticed, that I acknowledged your point.

> The idea to provide examples is good and something that I already had planned.

If you verbally attack me like that again, I will block you, revoking your access to this repository.

**Comment by Gourav1910** [comment]
> If you read my reply to your original comment, then you would have noticed, that I acknowledged your point.
> 
> > The idea to provide examples is good and something that I already had planned.
> 
> If you verbally attack me like that again, I will block you, revoking your access to this repository.

Actually you attacked me verbally and morally by giving a judgement that I was not friendly. I mean I don't even understand yet from where this thought came. I just write a request what I thought could be useful. That's it. But you start this debate by giving it an unexpected turn.🤦🏻‍♀️🤦🏻‍♀️
