### ISSUE TITLE
The plugin does not have any related examples, only interfaces. I tried but failed

### ISSUE THREAD

**Issue by zhoulonghao520** [mProjectsCode/obsidian-js-engine-plugin#4]
![image](https://github.com/mProjectsCode/obsidian-js-engine-plugin/assets/144794808/10e17156-f574-4390-bfea-444d288fb96c)

**Comment by mProjectsCode** [comment]
the second argument of `createTable` expects a two dimensional array, see [the docs](https://mprojectscode.github.io/obsidian-js-engine-plugin/classes/MarkdownAPI.MarkdownAPI.html#createTable).

```ts
let mdBuilder = engine.markdown.createBuilder();

mdBuilder.createTable(["Column 1", "Column 2"], [
	["data 1", "**data 2**"],
	["data 3", "data 4"],
]);

return mdBuilder;
```
