### ISSUE TITLE
FR: expose obsidian module apis

### ISSUE THREAD

**Issue by mariomui** [mProjectsCode/obsidian-js-engine-plugin#6]
As a user I want to be able to use all of obsidian components such as Notice and ButtonComponent.

**Comment by mProjectsCode** [comment]
I haven't found a good way to do this. The last time i tried i caused obsidian to crash xD

**Comment by mariomui** [comment]
I’ve seen templater do it. With your permission I can start work on it. It’s in current_functions_object in their codebase.

**Comment by mProjectsCode** [comment]
Feel free to make a PR for it. It's probably best if you pass the obsidian module into [here](https://github.com/mProjectsCode/obsidian-js-engine-plugin/blob/64782907e95bea22f2352e4735942be5995efb5f/jsEngine/engine/JsExecution.ts#L55) with the name `obsidian`.

**Comment by mariomui** [comment]
Not yet. You can take the ticket if you want.

**Comment by mProjectsCode** [comment]
Did that, will be part of the next release, alongside new docs.
