### ISSUE TITLE
Question : how to output mathjax?

### ISSUE THREAD

**Issue by sergeBoisse** [mProjectsCode/obsidian-js-engine-plugin#7]
Hello, thank you for this amazing obisidan plugin.
I wonder how you could render Latex/mathjax ? I tried
```
let str = '$\pi=3$';
return engine.markdown.create(str);
```
But the result was just "pi = 3" instead of "π = 3'

EDIT : ok, iI found it !  you need to escape the backslash  with another one : `$\\pi=3$`  

Perhaps you could add one example in the doc ?

**Comment by mProjectsCode** [comment]
An example of this will be part of the new docs.
